# 测试teams机器人 --- start
upstream teams {
    server 127.0.0.1:13978;
}
# 测试teams机器人 --- end


# 这里是测试teams机器人 start-----
location ^~/teams {
    set $md_real_ip '';
    if ($http_x_real_ip) {
        set $md_real_ip $http_x_real_ip;
    }
    if ($http_x_real_ip = '') {
        set $md_real_ip $remote_addr;
    }
    proxy_set_header   Host $host;
    proxy_set_header X-Real-IP $md_real_ip;
    rewrite ^/teams$ / break;
    rewrite ^/teams/(.*)$ /$1 break;
    proxy_pass http://teams;
}
# 这里是测试teams机器人 end--------